const CHANNEL='zveentv';
let cachedToken=null,cachedTokenExpiry=0,cachedLatest=null,cachedLatestExpiry=0;

function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}})}
function bytesToB64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64urlToBytes(value){const pad='='.repeat((4-value.length%4)%4);const raw=atob(value.replace(/-/g,'+').replace(/_/g,'/')+pad);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function hmac(value,secret){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(value)))}
async function sign(payload,secret){const body=bytesToB64url(new TextEncoder().encode(JSON.stringify(payload)));const sig=bytesToB64url(await hmac(body,secret));return `${body}.${sig}`}
async function verify(token,secret){if(!token||!secret||!token.includes('.'))return false;const[body,sig]=token.split('.');const expected=await hmac(body,secret);const actual=b64urlToBytes(sig||'');if(actual.length!==expected.length)return false;let diff=0;for(let i=0;i<actual.length;i++)diff|=actual[i]^expected[i];if(diff!==0)return false;try{const payload=JSON.parse(new TextDecoder().decode(b64urlToBytes(body)));return Number(payload.exp)>Date.now()}catch{return false}}
function sameString(a,b){a=new TextEncoder().encode(String(a??''));b=new TextEncoder().encode(String(b??''));if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a[i]^b[i];return diff===0}
async function getToken(env,force=false){const now=Date.now();if(!force&&cachedToken&&now<cachedTokenExpiry)return cachedToken;const r=await fetch('https://id.twitch.tv/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:env.TWITCH_CLIENT_ID,client_secret:env.TWITCH_CLIENT_SECRET,grant_type:'client_credentials'})});if(!r.ok)throw new Error(`oauth_${r.status}`);const d=await r.json();cachedToken=d.access_token;cachedTokenExpiry=now+Math.max(60,(Number(d.expires_in)||0)-60)*1000;return cachedToken}
async function twitchFetch(url,env,token){const r=await fetch(url,{headers:{'Client-Id':env.TWITCH_CLIENT_ID,Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`twitch_${r.status}`);return r.json()}
async function withToken(env,fn){let token=await getToken(env);try{return await fn(token)}catch(e){if(!String(e.message).includes('401'))throw e;cachedToken=null;cachedTokenExpiry=0;token=await getToken(env,true);return fn(token)}}
async function broadcasterId(env,token){const d=await twitchFetch(`https://api.twitch.tv/helix/users?login=${encodeURIComponent(CHANNEL)}`,env,token);const id=d.data?.[0]?.id;if(!id)throw new Error('broadcaster_not_found');return id}
function mapClip(c){return{id:c.id,title:c.title||'',url:c.url,thumbnail:c.thumbnail_url,views:Number(c.view_count)||0,duration:c.duration,creator:c.creator_name,createdAt:c.created_at}}
async function twitchStatus(env){if(!env.TWITCH_CLIENT_ID||!env.TWITCH_CLIENT_SECRET)return json({live:false,configured:false});try{const data=await withToken(env,async token=>twitchFetch(`https://api.twitch.tv/helix/streams?user_login=${encodeURIComponent(CHANNEL)}`,env,token));const s=Array.isArray(data.data)?data.data[0]:null;if(!s)return json({live:false,configured:true},200,{'Cache-Control':'public, max-age=15'});return json({live:true,configured:true,viewers:Number(s.viewer_count)||0,title:s.title||'',game:s.game_name||'',startedAt:s.started_at||null},200,{'Cache-Control':'public, max-age=15'})}catch(e){console.error('twitch-status',e);return json({live:false,configured:true,error:'temporarily_unavailable'})}}
async function clipsData(request,env){if(!env.TWITCH_CLIENT_ID||!env.TWITCH_CLIENT_SECRET)return json({clips:[],error:'twitch_not_configured'});const url=new URL(request.url);const requested=String(url.searchParams.get('ids')||'').split(',').map(decodeURIComponent).map(x=>x.trim()).filter(Boolean).slice(0,30);try{const clips=await withToken(env,async token=>{const id=await broadcasterId(env,token);if(requested.length){const p=new URLSearchParams();requested.forEach(x=>p.append('id',x));const d=await twitchFetch(`https://api.twitch.tv/helix/clips?${p}`,env,token);const byId=new Map((d.data||[]).map(c=>[c.id,c]));return requested.map(x=>byId.get(x)).filter(Boolean).map(mapClip)}if(cachedLatest&&Date.now()<cachedLatestExpiry)return cachedLatest;const p=new URLSearchParams({broadcaster_id:id,first:'20'});const d=await twitchFetch(`https://api.twitch.tv/helix/clips?${p}`,env,token);const latest=(Array.isArray(d.data)?d.data:[]).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,3).map(mapClip);cachedLatest=latest;cachedLatestExpiry=Date.now()+5*60*1000;return latest});return json({clips,mode:requested.length?'by_ids':'latest'},200,{'Cache-Control':'public, max-age=120'})}catch(e){console.error('clips-data',e);return json({clips:[],error:'fetch_failed'})}}
async function adminAuth(request,env){if(request.method!=='POST')return new Response('Method not allowed',{status:405});if(!env.ADMIN_PASSWORD||!env.ADMIN_SESSION_SECRET)return json({error:'admin_not_configured'},503);let body={};try{body=await request.json()}catch{}if(!sameString(body.password,env.ADMIN_PASSWORD))return json({error:'invalid_credentials'},401);return json({token:await sign({exp:Date.now()+8*60*60*1000},env.ADMIN_SESSION_SECRET)})}
function validate(data){return !!(data&&typeof data==='object'&&data.home&&typeof data.home.tagline==='string'&&data.about&&Array.isArray(data.about.paragraphs)&&Array.isArray(data.about.stats)&&data.equipment&&Array.isArray(data.equipment.pc)&&Array.isArray(data.equipment.audio)&&Array.isArray(data.equipment.accessories)&&Array.isArray(data.clips)&&data.clips.length<=30&&data.socials&&typeof data.socials==='object')}
async function triggerDeploy(env){if(!env.CLOUDFLARE_DEPLOY_HOOK)return false;try{const r=await fetch(env.CLOUDFLARE_DEPLOY_HOOK,{method:'POST'});if(!r.ok)throw new Error(`deploy_${r.status}`);return true}catch(e){console.error('deploy-hook',e);return false}}
async function adminSave(request,env){if(request.method!=='POST')return new Response('Method not allowed',{status:405});const auth=request.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!(await verify(token,env.ADMIN_SESSION_SECRET)))return json({error:'unauthorized'},401);if(!env.GITHUB_CONTENT_TOKEN)return json({error:'github_not_configured'},503);let parsed={};try{parsed=await request.json()}catch{}const data=parsed.data;if(!validate(data))return json({error:'invalid_data'},400);const repo=env.GITHUB_REPO||'ZveenTV/zveentv-website',branch=env.GITHUB_BRANCH||'main';const api=`https://api.github.com/repos/${repo}/contents/site-data.json`;const headers={Authorization:`Bearer ${env.GITHUB_CONTENT_TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'ZveenTV-Admin'};try{const currentRes=await fetch(`${api}?ref=${encodeURIComponent(branch)}`,{headers});if(!currentRes.ok)throw new Error(`read_${currentRes.status}`);const current=await currentRes.json();const content=bytesToB64url(new TextEncoder().encode(JSON.stringify(data,null,2)+'\n')).replace(/-/g,'+').replace(/_/g,'/');const padded=content+'='.repeat((4-content.length%4)%4);const saveRes=await fetch(api,{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({message:'Update website content from admin',content:padded,sha:current.sha,branch})});if(!saveRes.ok)throw new Error(`write_${saveRes.status}`);const saved=await saveRes.json();const deployTriggered=await triggerDeploy(env);return json({ok:true,commit:saved.commit?.sha||null,deployTriggered})}catch(e){console.error('admin-save',e);return json({error:'publish_failed'},500)}}
export async function onRequest(context){const path=new URL(context.request.url).pathname;switch(path){case'/api/twitch-status':return twitchStatus(context.env);case'/api/clips-data':return clipsData(context.request,context.env);case'/api/admin-auth':return adminAuth(context.request,context.env);case'/api/admin-save':return adminSave(context.request,context.env);default:return context.next()}}
