(function(){
  const PAGES=['index.html','about.html','equipment.html','clips.html','community.html','impressum.html','datenschutz.html','404.html'];
  const LABELS={'index.html':'Startseite','about.html':'Über mich','equipment.html':'Equipment','clips.html':'Clips','community.html':'Community','impressum.html':'Impressum','datenschutz.html':'Datenschutz','404.html':'404-Seite'};
  const SKIP=new Set(['SCRIPT','STYLE','NOSCRIPT','TEMPLATE','SVG']);
  let catalog={},active=PAGES[0],ready=false;
  const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  function elementPath(el,doc){const parts=[];while(el&&el.nodeType===1&&el!==doc.documentElement){let seg=el.tagName.toLowerCase();if(el.id){seg+='#'+el.id;parts.unshift(seg);break}const parent=el.parentElement;if(parent){const same=[...parent.children].filter(x=>x.tagName===el.tagName);if(same.length>1)seg+=`:nth-of-type(${same.indexOf(el)+1})`}parts.unshift(seg);el=parent}return parts.join('>')}
  function keyFor(page,node,doc){const p=node.parentElement;if(!p)return'';const texts=[...p.childNodes].filter(n=>n.nodeType===3);return page+'|'+elementPath(p,doc)+'|t'+Math.max(0,texts.indexOf(node))}
  function extract(doc,page){const out=[];const w=doc.createTreeWalker(doc.body,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||SKIP.has(p.tagName))return NodeFilter.FILTER_REJECT;return n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});let n;while(n=w.nextNode()){const text=n.nodeValue.trim();const key=keyFor(page,n,doc);if(key&&text)out.push({key,text})}return out}
  async function buildCatalog(){for(const page of PAGES){try{const r=await fetch('/'+page+'?cms_text_catalog='+Date.now(),{cache:'no-store'});const html=await r.text();catalog[page]=extract(new DOMParser().parseFromString(html,'text/html'),page)}catch{catalog[page]=[]}}ready=true;renderList()}
  function ensureData(){if(!state.data)return false;state.data.textOverrides??={};for(const p of PAGES)state.data.textOverrides[p]??={};return true}
  function installUi(){const nav=qs('#adminNav');const advanced=nav?.querySelector('[data-panel="advanced"]');if(nav&&!nav.querySelector('[data-panel="texts"]')){const b=document.createElement('button');b.dataset.panel='texts';b.textContent='Alle Texte';advanced?nav.insertBefore(b,advanced):nav.appendChild(b)}
    const main=qs('.admin-layout main');const adv=qs('#panel-advanced');if(main&&!qs('#panel-texts')){const sec=document.createElement('section');sec.className='admin-panel';sec.id='panel-texts';sec.innerHTML=`<div class="panel-head"><div class="eyebrow">Volltext-CMS</div><h2>Alle Texte</h2><p>Hier kannst du wirklich jeden statischen sichtbaren Text der öffentlichen Website überschreiben.</p></div><div class="note">Die speziellen Bereiche wie Startseite, Community oder SEO bleiben erhalten. Dieser Bereich ist die letzte Ebene und kann deren sichtbare Texte gezielt überschreiben.</div><div class="admin-card"><div class="field"><label>Seite</label><select id="textPageSelect"></select></div><div class="field"><label>Text suchen</label><input id="textSearch" placeholder="z. B. Twitch, Community, Impressum …"></div><div class="help" id="textCount"></div></div><div id="allTextRows"></div>`;adv?main.insertBefore(sec,adv):main.appendChild(sec);const sel=qs('#textPageSelect');for(const p of PAGES){const o=document.createElement('option');o.value=p;o.textContent=LABELS[p];sel.appendChild(o)}sel.onchange=e=>{active=e.target.value;renderList()};qs('#textSearch').oninput=renderList}
  }
  function renderList(){if(!ready||!ensureData()||!qs('#allTextRows'))return;const q=(qs('#textSearch')?.value||'').trim().toLowerCase();const rows=(catalog[active]||[]).filter(x=>!q||x.text.toLowerCase().includes(q)||(state.data.textOverrides[active]?.[x.key]||'').toLowerCase().includes(q));qs('#textCount').textContent=`${rows.length} Textfelder auf ${LABELS[active]}`;const wrap=qs('#allTextRows');wrap.innerHTML='';rows.forEach((item,i)=>{const box=document.createElement('div');box.className='admin-card';const current=state.data.textOverrides[active]?.[item.key];box.innerHTML=`<div class="mini-label">${i+1} · Original</div><div style="margin-bottom:10px;color:var(--text-muted);font-size:.86rem">${escapeHtml(item.text)}</div><div class="field" style="margin-bottom:8px"><label>Text auf der Website</label><textarea></textarea></div><button class="mini-btn" type="button">Auf Original zurücksetzen</button>`;const ta=box.querySelector('textarea');ta.value=current!==undefined?current:item.text;ta.oninput=e=>{ensureData();const v=e.target.value;if(v===item.text)delete state.data.textOverrides[active][item.key];else state.data.textOverrides[active][item.key]=v;markDirty()};box.querySelector('button').onclick=()=>{delete state.data.textOverrides[active][item.key];ta.value=item.text;markDirty()};wrap.appendChild(box)})}
  function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function waitForData(){installUi();if(state.data){ensureData();buildCatalog();return}setTimeout(waitForData,150)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',waitForData);else waitForData();
})();
