(function(){
  const polish=document.createElement('link');polish.rel='stylesheet';polish.href='/mobile-polish.css';document.head.appendChild(polish);
  function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
  function updateSocials(s){if(!s)return;document.querySelectorAll('a[href]').forEach(a=>{const h=a.getAttribute('href')||'';if(h.includes('twitch.tv/zveentv')&&s.twitch)a.href=s.twitch;else if(h.includes('discord.com/invite')&&s.discord)a.href=s.discord;else if(h.includes('youtube.com/@zveentv')&&s.youtube)a.href=s.youtube;else if(h.includes('instagram.com/zveentv')&&s.instagram)a.href=s.instagram;else if(h.includes('tiktok.com/@zveen.tv')&&s.tiktok)a.href=s.tiktok;});}
  function renderEquipment(target,rows){if(!target||!Array.isArray(rows))return;target.querySelectorAll('.equip-item').forEach(x=>x.remove());rows.forEach(r=>{const [label,value,url]=r;const el=document.createElement(url?'a':'div');el.className='equip-item';if(url){el.href=url;el.target='_blank';el.rel='noopener';}el.innerHTML=`<div><div class="label">${esc(label)}</div><div class="value${url?'':' unavailable'}">${esc(value)}${url?'':'<span class="tag-unavail">Nicht mehr erhältlich</span>'}</div></div><span class="ext">${url?'↗':'⊘'}</span>`;target.appendChild(el);});}
  function renderAbout(data){const card=document.querySelector('.about-page .player-card');if(card&&Array.isArray(data.about?.stats)){card.querySelectorAll('.stat-row').forEach(x=>x.remove());data.about.stats.forEach((r,i)=>{const row=document.createElement('div');row.className='stat-row';row.innerHTML=`<span class="label">${esc(r[0])}</span><span class="value${i===6?' accent':''}">${esc(r[1])}</span>`;card.appendChild(row);});}const wrap=document.querySelector('.about-page .about-text');if(!wrap)return;const lede=wrap.querySelector('p.lede');if(lede&&data.about?.lede)lede.textContent=data.about.lede;if(Array.isArray(data.about?.paragraphs)){wrap.querySelectorAll('p:not(.lede)').forEach(x=>x.remove());const cta=wrap.querySelector('.hero-cta');data.about.paragraphs.forEach(p=>{const el=document.createElement('p');el.textContent=p;wrap.insertBefore(el,cta);});}}
  function addDiscordToMobileMenu(socials){const nav=document.getElementById('navLinks');if(!nav||nav.querySelector('.mobile-discord-link'))return;const a=document.createElement('a');a.className='mobile-discord-link';a.href=socials?.discord||'https://discord.com/invite/sVWuKPpkG8';a.target='_blank';a.rel='noopener';a.textContent='Discord';nav.appendChild(a);}
  async function polishHome(){const box=document.getElementById('twitchEmbed');if(!box)return;try{const r=await fetch('/.netlify/functions/twitch-status',{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(!d.live){box.innerHTML='<div class="twitch-offline-card"><img src="assets/logo.png" alt=""><strong>Gerade nicht live.</strong><p>Der nächste gute Abend kommt. Bis dahin kannst du direkt auf Twitch vorbeischauen.</p><a href="https://www.twitch.tv/zveentv" target="_blank" rel="noopener">ZveenTV auf Twitch →</a></div>';}}catch(_){}}
  async function polishCuratedClips(){const grid=document.getElementById('curatedClipsGrid');if(!grid)return;setTimeout(async()=>{const cards=[...grid.querySelectorAll('.clip-popup-card[data-clip]')];const ids=cards.map(c=>c.dataset.clip).filter(Boolean);if(!ids.length)return;try{const r=await fetch('/.netlify/functions/clips-data?ids='+encodeURIComponent(ids.join(',')),{cache:'no-store'});if(!r.ok)return;const d=await r.json();const map=new Map((d.clips||[]).map(c=>[c.id,c]));cards.forEach(card=>{const c=map.get(card.dataset.clip);if(!c)return;card.dataset.title=c.title||'ZveenTV Highlight';card.dataset.url=c.url||card.dataset.url;const preview=card.querySelector('.clip-popup-preview');if(preview&&c.thumbnail){const old=preview.querySelector('iframe,img');const img=document.createElement('img');img.src=c.thumbnail;img.alt='';img.loading='lazy';old?.replaceWith(img);}const count=card.querySelector('.clip-view-count');if(count)count.textContent=(Number(c.views)||0).toLocaleString('de-DE')+' Aufrufe';});}catch(_){}} ,350);}
  async function boot(){let data;try{const r=await fetch('/site-data.json',{cache:'no-store'});if(!r.ok)return;data=await r.json();}catch(_){return;}window.ZVEEN_SITE_DATA=data;updateSocials(data.socials);addDiscordToMobileMenu(data.socials);const tagline=document.querySelector('.hero-home .tagline');if(tagline&&data.home?.tagline)tagline.textContent=data.home.tagline;renderAbout(data);const cols=document.querySelectorAll('.equipment-page .equip-col');renderEquipment(cols[0],data.equipment?.pc);renderEquipment(cols[1],data.equipment?.audio);renderEquipment(cols[2],data.equipment?.accessories);polishHome();polishCuratedClips();document.dispatchEvent(new CustomEvent('zveen:data',{detail:data}));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();